/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppPlayRouteImport } from './routes/_app/play'
import { Route as ApiOnboardingRouteImport } from './routes/api/onboarding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const ApiOnboardingRoute = ApiOnboardingRouteImport.update({
  id: '/api/onboarding',
  path: '/api/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play': typeof AppPlayRoute
  '/api/onboarding': typeof ApiOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play': typeof AppPlayRoute
  '/api/onboarding': typeof ApiOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/play': typeof AppPlayRoute
  '/api/onboarding': typeof ApiOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play' | '/api/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play' | '/api/onboarding'
  id: '__root__' | '/' | '/_app' | '/_app/play' | '/api/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiOnboardingRoute: typeof ApiOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/play': {
      id: '/_app/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/onboarding': {
      id: '/api/onboarding'
      path: '/api/onboarding'
      fullPath: '/api/onboarding'
      preLoaderRoute: typeof ApiOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppPlayRoute: typeof AppPlayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPlayRoute: AppPlayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiOnboardingRoute: ApiOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
